### ISSUE TITLE
Не работает или неправильно описана точность в вопросе NUMBER

### ISSUE THREAD

**Issue by tatyderb** [tatyderb/course_deploy#21]
https://stepik.org/lesson/378901/step/4?unit=366054

https://github.com/tatyderb/course_deploy/blob/master/examples/question_example.md

```
## NUMBER Ввод числа с указанной точностью

Можно задать вопрос, где ответ - число **с указанной точностью**. Точность пишется после `+-` после числа.

Чему равно $\pi$ ?

ANSWER: 3.1415 +- 0.01
```

Факт: не принимаются ответы 3.14, 3.1415, 3.15
Ожидаю: принимаются числа в диапазоне от [3.1415-0.01, 3.1415+0.01] ВКЛЮЧИТЕЛЬНО, т.е. 3.1515 тоже неплохое число (но на включительность я могу закрыть глаза).

**Comment by Nable80** [comment]
> 3.1415 ± 0.01

Пардон, что? За такую запись пальцы отбить линейкой должны были ещё в школе. Ставить так вопросы, как минимум, негуманно.

**Comment by tatyderb** [comment]
> > 3.1415 ± 0.01
> 
> Пардон, что? За такую запись пальцы отбить линейкой должны были ещё в школе. Ставить так вопросы, как минимум, негуманно.

Это же тестовый пример, на котором отлаживаемся. 
Или вопрос по выбранному формату задания точности? 
(Насчет +- в тексте задания - мой косяк, не осознала, что `+-` в маркдауне сольется в один знак  +- "плюс минус".)

**Comment by Nable80** [comment]
Вопрос о том что такая запись в принципе некорректна когда речь идёт про число с погрешностью.
Можно писать, ``3.14 ± 0.01`` или ``3.1415 ± 0.0001``, но не вот это. Внутренний физик должен испытывать боль при виде такой записи.

> в маркдауне сольется в один знак +- "плюс минус"

Не сольётся, это я на автопилоте так ввожу с клавиатуры (``<compose key>``, ``+``, ``-``).

**Comment by tatyderb** [comment]
Как указывать точность - на откуп создателям вопросов. Я же тестер, я же сразу тест сделала с плохой записью, которая должна была что-то сломать.
Разумно убрать такое из примеров. Согласна.
