### ISSUE TITLE
Сообщение о дефолтных секретках

### ISSUE THREAD

**Issue by tatyderb** [tatyderb/course_deploy#8]
Типичная ошибка при деплое - оставляют дефолтные секретки в auth.data

Надо проверять, не дефолтные ли секретки и если да, то выдавать как изменить:
Wrong client credentials. Go to https://stepik.org/oauth2/applications/ and write data into auth.py file.
CLIENT_ID - from ...
CLIENT_SECRET - from ...

Последние 2 строки сообщения написать те названия полей, что сейчас в их форме.
У меня какая-то странная запись из степиковского примера логина 
(client type = confidential, authorization grant type = client credentials)

**Comment by Tako-San** [comment]
Там когда создаешь приложение, чтобы секретку получить нужно выбрать client type и authorization grant type. Для этого и нужна эта запись

**Comment by tatyderb** [comment]
https://github.com/tatyderb/course_deploy/pull/12
